@startuml
'https://plantuml.com/activity-diagram-beta
|User|
start
:enter website;
|System|
if(logged in?) is (no) then
    |User|
    :login;
    if(already user?) is (yes) then
    else;
        |User|
        -> no;
        :create user;
        repeat :enter credentials;
        |System|
        repeat while (credentials valid?) is (no) not (yes);
    endif;
    |User|
    :login;
    repeat :enter credentials;
    |System|
    repeat while (credentials  valid?) is (no) not (yes);
else (yes);
end if;
if(User) is (normal user) then;
    |User|
    while (Everything wanted on list) is (no)
        :add cupcake;
    endwhile (yes)
    while (something unwanted on list) is (yes)
        :remove cupcakes or adjust amounts;
    endwhile (no);
    :confirm order;
    |System|
    if (logged in?) is (no) then;
        :goto log in page;
        detach;
    else (yes);
    endif;
    :add order to system;
    detach;
else if(wants to add order) is (yes) then;
        :proceed as normal user;
        detach;
else (admin);
    |Worker|
    'adding workers work flow when dealing with orders
end if;
@enduml
