@startuml
'https://plantuml.com/activity-diagram-beta
|Kunde|
start
:enter website;
repeat
if(wanna login?) then(no);
else (yes)
partition #lightBlue Login {
:login website;
if(already user?) then(yes);
else (no)
:create user;
repeat
:enter credentials;
|website|
repeat while (check if credentials are valid?) is (no)
-> yes;
|Kunde|
end if;
:login;
repeat
:enter credentials;
|website|
repeat while (check if credentials are valid?) is (no)
-> yes;
}
end if;
|Kunde|
partition #lightPink create cupcakes order {
repeat
:customize cupcakes;
repeat while (done customizing cupckas?) is (no)
->yes;
}
partition #lightGreen view basket {
:basket;
repeat
|Kunde|
:customize order;
repeat while (done?) is (no)
}
repeat while(logged in) is (no)
-> yes;
|Kunde|
:submit order;
|website|
:placing order;
partition #Orange getting cupcakes {
fork
|Kunde|
:receipt]
:go to shop;
fork again;
|shop|
:get order and create cupcakes;
:cupcakes]
:order ready for pick up;
|Kunde|
|shop|
end fork;
:get cupcakes and eat them;
}
stop
@enduml